Repository togather-2024/togather-backend, pull requests merged in 2024-02, with the labels that each got.

#1 Feat: Added member-related table
  .github/ISSUE_TEMPLATE/feature_request.md
  sql/member_related_table.sql
Labels: DB

#4 Feature: Add CREATE sql files for party room related tables
  togather-common/src/main/resources/sql/CREATE_member_related_table.sql
  togather-common/src/main/resources/sql/CREATE_party_room_related_table.sql
Labels: DB

#7 Feat: Member, Email Verification Entity
  .github/pull_request_template.md
  togather-common/src/main/java/com/togather/email_verification/model/EmailVerification.java
  togather-common/src/main/java/com/togather/email_verification/repository/EmailVerificationRepository.java
  togather-common/src/main/java/com/togather/member/model/Member.java
  togather-common/src/main/java/com/togather/member/model/Role.java
  togather-common/src/main/java/com/togather/member/repository/MemberRepository.java
  togather-common/src/main/resources/sql/CREATE_member_related_table.sql
Labels: DB

#9 feat: Add email configuration and sending email
  togather-common/build.gradle
  togather-common/src/main/java/com/togather/config/email/EmailConfig.java
  togather-common/src/main/java/com/togather/email_verification/converter/EmailVerificationDtoConverter.java
  togather-common/src/main/java/com/togather/email_verification/dto/EmailVerificationDto.java
  togather-common/src/main/java/com/togather/email_verification/model/EmailVerification.java
  togather-common/src/main/java/com/togather/email_verification/service/EmailVerificationService.java
  togather-common/src/main/java/com/togather/member/converter/MemberDtoConverter.java
  togather-common/src/main/java/com/togather/member/dto/MemberDto.java
  togather-common/src/main/java/com/togather/member/model/Member.java
  togather-common/src/main/java/com/togather/member/model/Role.java
  togather-common/src/main/java/com/togather/member/repository/MemberRepository.java
  togather-common/src/main/resources/application-mysql.yml
  togather-web/src/main/java/com/togather/emailVerification/EmailVerificationController.java
Labels: enhancement

#13 Feat: Validation of email accuracy & Overall member service
  togather-common/src/main/java/com/togather/email_verification/converter/EmailVerificationConverter.java
  togather-common/src/main/java/com/togather/email_verification/repository/EmailVerificationRepository.java
  togather-common/src/main/java/com/togather/email_verification/service/EmailVerificationService.java
  togather-common/src/main/java/com/togather/member/converter/MemberConverter.java
  togather-common/src/main/java/com/togather/member/converter/MemberDtoConverter.java
  togather-common/src/main/java/com/togather/member/dto/MemberDto.java
  togather-common/src/main/java/com/togather/member/model/Member.java
  togather-common/src/main/java/com/togather/member/model/MemberDto.java
  togather-common/src/main/java/com/togather/member/model/MemberInfoDto.java
  togather-common/src/main/java/com/togather/member/model/Role.java
  togather-common/src/main/java/com/togather/member/repository/MemberRepository.java
  togather-common/src/main/java/com/togather/member/service/MemberService.java
  togather-common/src/main/java/com/togather/partyroom/core/converter/PartyRoomConverter.java
  togather-web/src/main/java/com/togather/emailVerification/EmailVerificationController.java
Labels: enhancement

#16 feat: Implemented party room reservation registration
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  togather-common/src/main/java/com/togather/email_verification/dto/EmailVerificationDto.java
  togather-common/src/main/java/com/togather/member/model/Member.java
  togather-common/src/main/java/com/togather/member/model/Role.java
  togather-common/src/main/java/com/togather/member/service/MemberService.java
  togather-common/src/main/java/com/togather/partyroom/core/repository/PartyRoomOperationDayRepository.java
  togather-common/src/main/java/com/togather/partyroom/core/service/PartyRoomService.java
  togather-common/src/main/java/com/togather/partyroom/payment/model/PaymentStatus.java
  togather-common/src/main/java/com/togather/partyroom/reservation/converter/PartyRoomReservationConverter.java
  togather-common/src/main/java/com/togather/partyroom/reservation/model/PartyRoomReservationDto.java
  togather-common/src/main/java/com/togather/partyroom/reservation/repository/PartyRoomReservationRepository.java
  togather-common/src/main/java/com/togather/partyroom/reservation/service/PartyRoomReservationService.java
  togather-web/src/main/java/com/togather/emailVerification/EmailVerificationController.java
  togather-web/src/main/java/com/togather/partyroom/core/PartyRoomController.java
  togather-web/src/main/java/com/togather/partyroom/reservation/PartyRoomReservationController.java
Labels: enhancement, question

#18 feat: Implemented party room reservation deletion and search by guest
  togather-common/src/main/java/com/togather/member/model/MemberDto.java
  togather-common/src/main/java/com/togather/member/service/MemberService.java
  togather-common/src/main/java/com/togather/partyroom/reservation/model/PartyRoomReservationDto.java
  togather-common/src/main/java/com/togather/partyroom/reservation/repository/PartyRoomReservationRepository.java
  togather-common/src/main/java/com/togather/partyroom/reservation/service/PartyRoomReservationService.java
  togather-web/src/main/java/com/togather/emailVerification/EmailVerificationController.java
  togather-web/src/main/java/com/togather/partyroom/reservation/PartyRoomReservationController.java
Labels: enhancement
